chat_model:
    google: gemini-2.5-flash-preview-04-17
    # google: gemini-2.5-pro-preview-03-25
    ollama: llama3.2

embedding_model:
    google: text-embedding-005   
    ollama: mxbai-embed-large
