services:
  app:
    image: invoice-agent:latest
    platform: linux/amd64
    # hostname: my-repo
    build:
      context: .
      dockerfile: invoice.Dockerfile
    ports:
      - 5000:5000
    container_name: invoice-agent
    volumes:
      - /Users/avosseler/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
