services:  
  app:
    image: invoice-agent:latest
    platform: linux/amd64
    # hostname: my-repo
    build:
      context: .
      dockerfile: invoice.Dockerfile
    ports:
      - 5000:5000
    container_name: invoice-agent
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT}
